In [2]:
import numpy as np

In [3]:
just_arr = np.array([[1, 2, 3], [4, 5, 6]])
just_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
zero_arr = np.zeros((3, 2, 4))
zero_arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
just_arr.shape

(2, 3)

In [6]:
just_arr.dtype

dtype('int64')

In [7]:
just_arr[1, 1]

np.int64(5)

In [8]:
slice_arr = just_arr[::-1, ::2]
slice_arr

array([[4, 6],
       [1, 3]])

In [9]:
just_arr += just_arr
just_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
just_arr.mean()

np.float64(7.0)